<?php
/**
 * Created by Hisune EchartsPHP AutoGenerate.
 * @author: Hisune <hi@hisune.com>
 */

namespace Hisune\EchartsPHP\Doc\IDE;

use Hisune\EchartsPHP\Property;

/**
 * @property boolean $show Default: false
 *    Whether to enable ARIA. When enabled, there should be an aria-label label.
 *
 * @property string $description
 *    By default, the description is generated by our algorithm based on charts. If user want to set the description totally, description should be set to the whole description.
 *     This is useful when single data values cannot represent what the chart means. For example, if the chart is a map containing many scatter points. Default description can only show the data, but the users may find it hard to understand what the user mean. In this case, description should be set to discribe the meaning of chart.
 *
 * @property Aria\General $general
 *    General discription of chart.
 *
 * @property Aria\Series $series
 *    Series-related configures.
 *
 * @property Aria\Data $data
 *    Data-related configures.
 *
 * {_more_}
 */
class Aria extends Property {}